python/djangoWebDev1/ch05/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name='index'),

    url(r'^book/$', views.BookList.as_view(), name='book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name='author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name='publisher_list'),
    
    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name='author_detail'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetail.as_view(), name='putlisher_detail')
]

python/djangoWebDev1/ch05/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books'))
]

python/djangoWebDev1/ch05/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField("Author")
    publisher = models.ForeignKey('Publisher')
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    saluation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

python/djangoWebDev1/ch05/books/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Publisher, Author

#-- TemplateView
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super(BooksModelView, self).get_context_data(**kwargs)
        context['object_list'] = ['Book', 'Author', 'Publisher']
        return context;

#-- ListView
class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

#-- DetailView
class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

python/djangoWebDev1/ch05/books/templates/books/author_detail.html
{% extends 'base_book.html' %}

{% block content %}
<h1>{{object.name}}</h1>
<p>{{object.salutation}}</p>
<li>Email: {{object.email}}</li>
{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/author_list.html
{% extends 'base_books.html' %}

{% block content %}

    <h2>Author List</h2>
    <ul>
    {% for author in object_list %}
        <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
    {% endfor %}
    </ul>

{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/book_detail.html
{% extends 'base_book.html' %}

{% block content %}

    <h1>{{ object.title }}</h1>
    <br>
    <li>Authors : 
        {% for author in object.authors.all %}
            {{ author }}
            {% if not forloop.last %},{% else %}{% endif %}
        {% endfor %}
    </li>
    <li>
        Publisher : {{ object.publisher }}
    </li>
    <li>
        Publication date : {{ object.publication_date }}
    </li>

{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management</h2>
    <ul>
        {% for modelname in object_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/publisher_detail.html
{% extends 'base_book.html' %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address: {{ object.address }}</li>

{% endblock content %}

python/djangoWebDev1/ch05/books/templates/books/publisher_list.html
{% extends 'base_book.html' %}

{% block content %}

    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>

{% endblock content%}

python/djangoWebDev1/ch05/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}"/>
    <title>{% block title %}My Amazing Site{% endblock title %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock sidebar %}
        <br>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

python/djangoWebDev1/ch05/templates/base_book.html
{% extent 'base.html' %}

<title>{% block title %}Books Application Site{%endblock%}</title>

{% block sidebar%}
{{block.super}}
<ul>
    <li><a href="/books/">Books_Home</a></li>
</ul>
{% endblock sidebar %}